  google_ads: {
    name: 'Google Ads',
    icon: 'G',
    iconClass: 'icon-google',
    description: 'Search, display, video, and shopping advertising platform',
    whatItDoes: 'Google Ads powers paid search, display, YouTube, and shopping campaigns. Fivetran syncs campaign structures, ad performance metrics, keyword data, and conversion tracking across all campaign types.',
    usefulFor: 'Paid media teams, performance marketing, SEM/PPC management, cross-channel attribution, marketing ROI analysis',
    docsUrl: 'https://fivetran.com/docs/connectors/applications/google-ads',
    tables: [
      { name: 'CAMPAIGN', whatContains: 'All campaigns with name, status, budget, bidding strategy, network settings, and start/end dates', whyMatters: 'Top-level grouping for all ad spend and performance reporting', keyCallouts: 'Campaign types include Search, Display, Video, Shopping, Performance Max, and App. Status values: ENABLED, PAUSED, REMOVED.' },
      { name: 'AD_GROUP', whatContains: 'Ad groups within campaigns — targeting settings, default bids, status, and ad rotation preferences', whyMatters: 'Middle tier of the campaign hierarchy where targeting and bidding are set', keyCallouts: 'Each ad group belongs to one campaign. Bid adjustments and audience targeting are configured at this level.' },
      { name: 'AD', whatContains: 'Individual ad creatives — headlines, descriptions, display URLs, final URLs, and ad type', whyMatters: 'Tracks which specific creatives are running and enables A/B testing analysis', keyCallouts: 'Responsive search ads have multiple headlines/descriptions stored as arrays. Expanded text ads (legacy) have fixed headline fields.' },
      { name: 'KEYWORD', whatContains: 'Keywords with match type, bid, quality score, status, and approval status', whyMatters: 'Core of search campaign optimization — shows what terms you are bidding on and their quality', keyCallouts: 'Match types: EXACT, PHRASE, BROAD. Quality Score components: expected CTR, ad relevance, landing page experience (each rated ABOVE_AVERAGE, AVERAGE, BELOW_AVERAGE).' },
      { name: 'CAMPAIGN_STATS', whatContains: 'Daily performance metrics per campaign — impressions, clicks, cost, conversions, CTR, average CPC', whyMatters: 'Primary table for spend tracking, ROI calculations, and trend analysis', keyCallouts: 'Metrics are aggregated daily. Cost is in micros (divide by 1,000,000 for actual currency). Conversions may update retroactively within the attribution window.' }
    ],
    knownIssues: [
      { category: 'Data Integrity', title: 'Metrics Arrive With Up to 3-Hour Delay', preview: 'Recent campaign data not yet visible in destination', rootCause: 'The Google Ads API has an inherent reporting delay of up to 3 hours. Click, impression, and conversion data is not available in real time from the API.', impact: 'Dashboards showing "today\'s performance" will be incomplete. Stakeholders may see stale numbers and assume campaigns are underperforming.', resolution: 'Set expectations that Google Ads data has a built-in lag. Design dashboards to show "as of" timestamps. Avoid real-time alerting on Google Ads metrics — use the Google Ads UI for intra-day monitoring.' },
      { category: 'Data Integrity', title: 'Conversion Data Updates Retroactively', preview: 'Conversion counts change days after the click occurred', rootCause: 'Google Ads attributes conversions back to the original click date, not the conversion date. Conversions can be reported up to 90 days after the click depending on the attribution window configured in the account.', impact: 'Historical conversion numbers shift over time. Reports pulled on different days for the same date range will show different totals. CPA and ROAS metrics are unstable until the attribution window closes.', resolution: 'Wait 7-14 days before treating conversion data as final. Use Fivetran\'s conversion window re-sync feature to keep historical data updated. Document the attribution window setting for each conversion action in the account.' },
      { category: 'Data Integrity', title: 'Click vs Impression Attribution Window Mismatch', preview: 'Click-based and impression-based metrics tell conflicting stories', rootCause: 'Search campaigns attribute conversions to clicks, while Display and YouTube campaigns can attribute to view-throughs (impressions). Default attribution windows differ: 30 days for clicks, 1 day for view-throughs. These can be customized per conversion action.', impact: 'Cross-campaign comparisons are misleading when mixing click-attributed search conversions with view-through display conversions. Total conversions can appear inflated.', resolution: 'Segment reporting by campaign type (Search vs Display vs Video). Document the attribution model and window for each conversion action. Consider using data-driven attribution for consistent cross-channel measurement.' },
      { category: 'Data Integrity', title: 'Currency Values in Micros', preview: 'Cost and bid values appear as very large numbers', rootCause: 'Google Ads API returns all monetary values in micros (1/1,000,000 of the currency unit). A $5.00 CPC is returned as 5000000.', impact: 'Reports show wildly inflated numbers if analysts don\'t know to divide by 1,000,000. Budget and spend dashboards will be off by a factor of a million.', resolution: 'Apply the conversion in your transformation layer: cost_actual = cost / 1000000. Document this in your data dictionary. The dbt_google_ads package handles this automatically.' },
      { category: 'Data Integrity', title: 'Report Segment Granularity Causes Row Explosion', preview: 'Adding segments dramatically increases row count and MAR', rootCause: 'When report tables include segments (device, network, click type, ad network type), each combination creates a separate row. A single campaign-day can explode into dozens of rows across segments.', impact: 'Unexpected MAR increases. Warehouse storage grows quickly. Queries without proper aggregation will double-count metrics.', resolution: 'Only enable segments you actually need for analysis. Be aware that rows with segments cannot be simply summed — you must aggregate at the desired level. Review enabled segments in the Schema tab and disable any that are not needed.' },
      { category: 'Setup', title: 'MCC vs Individual Account Setup', preview: 'Choosing between manager account and individual account connections', rootCause: 'Google Ads supports both individual account connections and Manager (MCC) account connections. MCC connections sync all child accounts under one connector. Individual connections sync only that specific account.', impact: 'Using MCC: one connector covers all accounts but syncs everything. Using individual: more control but requires managing multiple connectors. Switching between approaches requires re-setup.', resolution: 'For agencies or multi-account setups, use MCC — it\'s more manageable. For single-account advertisers, use the individual account. When using MCC, use Fivetran\'s account filtering to exclude accounts you don\'t need. Each child account creates a separate schema.' },
      { category: 'Setup', title: 'OAuth Scoping and Permissions', preview: 'Insufficient OAuth permissions block data sync', rootCause: 'The authenticating Google account must have at least read-only access to the Google Ads account. For MCC setups, the account must have access at the manager level. Google\'s OAuth consent screen may not request the ads-specific scope.', impact: 'Connector authenticates successfully (Google login works) but then fails to pull any ads data because the OAuth token lacks the Google Ads API scope.', resolution: 'Ensure the authenticating user has "Standard" or "Read-only" access in Google Ads (not just Google account access). For MCC, the user must have admin or standard access at the manager level. Re-authorize the connection if permissions were granted after initial setup.' },
      { category: 'Data Integrity', title: 'Historical Data Limited to Account Lifetime', preview: 'Cannot pull data from before account creation', rootCause: 'Google Ads API provides data only from the account\'s creation date. Unlike some platforms, there is no archive API. The initial sync pulls all available historical data, which depends on the Google Ads account age.', impact: 'New Google Ads accounts will have limited history. Accounts migrated between MCC structures may lose visibility into pre-migration data.', resolution: 'Verify the account\'s start date in Google Ads before setting customer expectations about historical depth. For migrated accounts, check if the original account still has historical data accessible.' },
      { category: 'Data Integrity', title: 'Smart Campaign and Performance Max Limited Data', preview: 'Automated campaign types have restricted reporting fields', rootCause: 'Smart Campaigns and Performance Max campaigns use Google\'s AI to manage targeting and creatives. Google restricts the granularity of data available through the API for these campaign types — keyword-level, ad-level, and placement-level data is largely unavailable.', impact: 'Analysts expecting the same granularity as standard Search campaigns will find gaps. Cannot perform keyword-level or creative-level analysis on these campaign types.', resolution: 'Set expectations that automated campaign types offer aggregate-level reporting only. Use the Google Ads UI for detailed Performance Max insights (asset group reporting). Factor campaign type into your reporting design.' },
      { category: 'Errors', title: 'API Quota Exceeded for Large Accounts', preview: 'Sync fails due to Google Ads API rate limits', rootCause: 'Google Ads API enforces daily request quotas and per-minute rate limits. Accounts with hundreds of campaigns or millions of keywords can exhaust quotas during sync.', impact: 'Sync fails partway through — some tables updated, others stale. Creates data inconsistencies within the same sync window.', resolution: 'Reduce sync frequency for very large accounts. Disable report tables and segments you don\'t need. Contact Fivetran support to optimize the sync strategy for high-volume accounts.' },
      { category: 'Syncs', title: 'Re-Sync Window for Statistical Tables', preview: 'Fivetran re-syncs recent days to capture retroactive updates', rootCause: 'Because Google Ads retroactively updates metrics (especially conversions), Fivetran re-syncs a configurable window of recent days on each sync. The default conversion window is typically 30 days.', impact: 'MAR increases because rows within the re-sync window are re-processed every sync. Larger conversion windows mean more data re-synced each time.', resolution: 'Adjust the conversion window in Fivetran connector settings to match your actual Google Ads attribution window. Shorter windows reduce MAR but risk missing late-arriving conversions. The 30-day default is appropriate for most accounts.' },
      { category: 'FAQ', title: 'Why Do Google Ads Numbers Not Match the Google Ads UI?', preview: 'Slight discrepancies between Fivetran data and the Google Ads dashboard', rootCause: 'The Google Ads UI applies real-time data, includes invalid click adjustments live, and may use different attribution models than what the API returns. Additionally, the UI defaults to "All conversions" while the API may return only primary conversions depending on configuration.', impact: 'Small discrepancies (typically under 5%) between warehouse data and the Google Ads dashboard. Stakeholders may question data accuracy.', resolution: 'Document that minor discrepancies are expected and stem from timing differences and attribution model variations. Compare using the same date range and conversion columns. Use "conversions" (not "all_conversions") to match the UI default. Allow 72 hours after the reporting period for numbers to stabilize.' }
    ]
  },
  facebook_ads: {
    name: 'Facebook Ads',
    icon: 'F',
    iconClass: 'icon-facebook',
    description: 'Social advertising across Facebook, Instagram, Messenger, and Audience Network',
    whatItDoes: 'Facebook Ads (Meta) manages paid advertising across the Meta family of apps. Fivetran syncs campaign hierarchies, ad creatives, audience targeting, and performance insights including reach, impressions, and conversion events.',
    usefulFor: 'Social media marketing teams, demand generation, B2C acquisition, brand awareness campaigns, cross-platform attribution',
    docsUrl: 'https://fivetran.com/docs/connectors/applications/facebook-ads',
    tables: [
      { name: 'CAMPAIGN', whatContains: 'All campaigns with name, status, objective (awareness, traffic, conversions, etc.), budget type, and spend limits', whyMatters: 'Top-level container for all ad spend — defines the marketing objective and budget allocation', keyCallouts: 'Objective field changed with ODAX (Outcome-Driven Ad Experiences) rollout. Legacy objectives map to new simplified objectives. Status values: ACTIVE, PAUSED, DELETED, ARCHIVED.' },
      { name: 'AD_SET', whatContains: 'Ad sets with targeting criteria, placement settings, schedule, bid strategy, and budget', whyMatters: 'Controls who sees ads, where they appear, and how much is bid — the core targeting layer', keyCallouts: 'Targeting field contains nested JSON with demographics, interests, behaviors, and custom audiences. Placements can be automatic or manual (Facebook Feed, Instagram Stories, etc.).' },
      { name: 'AD', whatContains: 'Individual ads with creative references, status, tracking specs, and UTM parameters', whyMatters: 'Links the creative asset to the targeting and budget — the actual unit being served to users', keyCallouts: 'Creative content is in the CREATIVE table (joined via creative_id). Ad-level tracking_specs define conversion events to optimize for.' },
      { name: 'AD_INSIGHTS', whatContains: 'Daily performance metrics — impressions, reach, clicks, spend, actions (conversions), cost per action, frequency', whyMatters: 'Primary reporting table for spend analysis, ROAS calculations, and campaign optimization', keyCallouts: 'Actions are nested arrays containing event types (purchases, leads, page views) and their counts. Breakdowns (age, gender, placement, device) create separate rows. Spend is in account currency.' },
      { name: 'CREATIVE', whatContains: 'Ad creative assets — image URLs, video thumbnails, body text, headlines, call-to-action, link URLs', whyMatters: 'Enables creative performance analysis across campaigns and A/B test evaluation', keyCallouts: 'Dynamic creatives have multiple assets stored in asset_feed_spec. Creative reuse across ads is tracked via creative ID joins.' }
    ],
    knownIssues: [
      { category: 'Data Integrity', title: 'iOS 14+ Privacy Impact on Attribution', preview: 'Significant data gaps due to Apple App Tracking Transparency (ATT)', rootCause: 'Apple\'s iOS 14.5+ ATT framework requires user opt-in for cross-app tracking. Approximately 75-80% of iOS users opt out. Meta cannot track conversions from opted-out users, leading to underreported and delayed conversion data via the Aggregated Event Measurement (AEM) protocol.', impact: 'Conversion counts are significantly underreported (often 30-50% lower than actual for iOS-heavy audiences). Attribution windows shortened. Breakdown data (age, gender) is limited for iOS conversions. Modeled conversions partially fill the gap but are estimates.', resolution: 'Explain to stakeholders that post-iOS 14 data is structurally incomplete — this is an industry-wide Meta limitation, not a Fivetran issue. Use Meta\'s Conversions API (server-side) alongside the pixel for better coverage. Compare trends over time rather than absolute numbers. Consider Meta\'s modeled reporting as directional guidance.' },
      { category: 'Data Integrity', title: '28-Day Attribution Window Removed', preview: 'Historical comparison breaks due to attribution window change', rootCause: 'In January 2021, Meta removed the 28-day click and 28-day view attribution windows. The maximum is now 7-day click and 1-day view. Historical data that used 28-day windows cannot be directly compared to current data.', impact: 'Year-over-year comparisons are misleading — pre-2021 data captured more attributed conversions under the longer window. Current conversion counts appear lower even if actual performance is unchanged.', resolution: 'Document the attribution window change date in your reporting. Avoid direct YoY comparisons spanning the January 2021 cutoff. Use 7-day click as the standard window going forward. If historical data used 28-day click, note that current numbers will appear 15-25% lower for the same actual performance.' },
      { category: 'Data Integrity', title: 'Data Discrepancies With Facebook Ads Manager UI', preview: 'Fivetran data doesn\'t exactly match the Ads Manager dashboard', rootCause: 'The Facebook Ads Manager UI applies unique reach calculations, real-time data, and may use different default attribution settings than the API. The API also returns data with a slight delay compared to the UI. Additionally, Ads Manager may apply cross-campaign deduplication for reach that the API does not.', impact: 'Expect 2-10% discrepancies between Fivetran data and the Ads Manager dashboard. Reach metrics are the most divergent because reach deduplication is handled differently.', resolution: 'Document that minor discrepancies are expected. Use the same attribution window and date range when comparing. Reach metrics will always differ because the API cannot deduplicate across campaigns the way the UI does. Allow 48-72 hours after the reporting period for numbers to stabilize.' },
      { category: 'Data Integrity', title: 'Breakdowns Cause Row Duplication and Inflated Metrics', preview: 'Summing metrics across breakdown rows produces incorrect totals', rootCause: 'When AD_INSIGHTS includes breakdowns (age, gender, placement, device, country), each breakdown combination creates a separate row. The "actions" array in each row only reflects that segment. However, reach is deduplicated per breakdown but not across breakdowns — summing reach across age groups will overcount.', impact: 'Analysts summing metrics across breakdown rows will get inflated totals for reach and frequency. Impressions and spend can be summed, but reach cannot. Reports may show impossible numbers (reach > population).', resolution: 'Never sum reach across breakdown rows — use the non-breakdown row for total reach. Impressions, clicks, and spend are safely summable across breakdowns. Document which metrics are additive and which are not. Consider creating separate reporting tables for breakdown-level vs aggregate analysis.' },
      { category: 'Data Integrity', title: 'API Deprecation Cycles Break Historical Reports', preview: 'Meta API version upgrades can change data structure and availability', rootCause: 'Meta depreciates API versions roughly every 2 years and frequently changes field names, removes metrics, or alters data structures between versions. Fivetran upgrades API versions to stay current, which can change column names or data formats.', impact: 'Schema changes can break downstream dashboards and reports. Historical data may not have the same fields as current data. Deprecated metrics disappear without warning.', resolution: 'Monitor Fivetran release notes for Facebook Ads connector updates. Build resilient downstream models that handle null/missing columns gracefully. Use Fivetran\'s schema change notifications to catch changes early.' },
      { category: 'Setup', title: 'Ad Account Access Permissions', preview: 'Connector authenticates but cannot access ad accounts', rootCause: 'The authenticating Facebook user must have at least "Advertiser" role on the specific ad account(s) in Business Manager. Having a personal Facebook account is not sufficient — the user must be added to Business Manager and granted access to each ad account individually.', impact: 'Connector shows "Connected" but syncs no data, or only syncs data from some accounts. No error message may appear — tables are simply empty.', resolution: 'Verify in Meta Business Manager: Business Settings > Ad Accounts > select account > People. Ensure the authenticating user is listed with at least Advertiser access. For multi-account setups, the user needs access to each account. Use a system user token for more stable long-term access.' },
      { category: 'Data Integrity', title: 'Custom Conversion Tracking Gaps', preview: 'Custom conversions not appearing in synced data', rootCause: 'Custom conversions require the Facebook Pixel to be properly installed and firing on the target website. Server-side Conversions API events may not appear in the same reporting tables as pixel events. Custom conversion rules based on URL patterns can silently break when website URLs change.', impact: 'Missing or incomplete conversion data in the warehouse. ROAS calculations are inaccurate. Optimization signals are lost.', resolution: 'Verify pixel installation using Facebook Pixel Helper Chrome extension. Check custom conversion definitions in Events Manager for broken URL rules. Ensure Conversions API is sending events with matching event_id for deduplication. Custom conversions appear in the actions array — look for the specific action_type.' },
      { category: 'Data Integrity', title: 'Page-Level Reporting Limitations', preview: 'Organic vs paid page metrics cannot be cleanly separated', rootCause: 'Facebook Ads API focuses on paid advertising metrics. Page-level organic metrics (page likes, organic reach, post engagement) come from the Facebook Pages API, which is a separate Fivetran connector. Paid promotion of organic posts blurs the line between paid and organic attribution.', impact: 'Cannot build a unified paid + organic performance view from the Facebook Ads connector alone. Promoted post metrics may be split between the two data sources.', resolution: 'Use the Facebook Pages connector alongside the Facebook Ads connector for a complete picture. Join on post_id where available. Distinguish between paid and organic metrics using the "actions" breakdown by action_type.' },
      { category: 'Data Integrity', title: 'Data Retention and Historical Limits', preview: 'Very old campaign data may not be available via the API', rootCause: 'Meta retains detailed reporting data for approximately 37 months. After that, data may be summarized or unavailable via the API. Additionally, deleted campaigns are only available for a limited time after deletion.', impact: 'Multi-year trend analysis may have gaps for older periods. Deleted campaign data disappears from the API after approximately 2 years.', resolution: 'Fivetran preserves data in the warehouse even after Meta stops serving it via the API. Ensure your initial sync captures all needed history. Do not delete old campaigns in Meta if you need ongoing access to their data — archive them instead (ARCHIVED status keeps API access).' },
      { category: 'Errors', title: 'Token Expiration and Re-Authentication', preview: 'Sync stops working after token expires', rootCause: 'Facebook user access tokens expire after approximately 60 days. System user tokens (from Business Manager) are long-lived but can still be invalidated by password changes, account security events, or Business Manager admin actions.', impact: 'Sync silently stops — data becomes stale. No new data flows until re-authentication. Can go unnoticed if monitoring is not in place.', resolution: 'Use a system user token from Business Manager for more stable access (tokens last up to 60 days and can be refreshed). Set up Fivetran sync failure alerts. Re-authenticate in Fivetran when token expires: Setup tab > Edit connection > Re-authorize. Consider the non-expiring system user token option in Business Manager.' },
      { category: 'Syncs', title: 'Large Account Sync Duration', preview: 'Syncs take hours for accounts with thousands of campaigns', rootCause: 'Meta\'s API rate limits are aggressive — especially for the Insights endpoint. Accounts with many active campaigns, ad sets, and ads require thousands of API calls. Breakdowns multiply the number of API calls needed.', impact: 'Sync duration can exceed 6-8 hours for large accounts. Data freshness suffers. MAR increases with more breakdown rows.', resolution: 'Reduce the number of enabled breakdowns to only those needed. Disable historical ad sets and campaigns that are no longer relevant. Consider splitting very large ad accounts into separate connectors if possible. Contact Fivetran support for sync optimization on high-volume accounts.' },
      { category: 'FAQ', title: 'Why Are My Facebook Ads Costs Different From Other Channels?', preview: 'Understanding Meta\'s unique cost and billing model', rootCause: 'Meta uses an auction-based pricing model with different optimization events (impressions, link clicks, conversions). Cost metrics like CPC can mean "cost per all clicks" (including reactions, comments) or "cost per link click" depending on the field used.', impact: 'Comparing Facebook CPC to Google Ads CPC is misleading without aligning definitions. Stakeholders may draw incorrect conclusions about relative channel efficiency.', resolution: 'Use cost_per_inline_link_click for link-click CPC (comparable to Google Ads CPC). Use cost_per_action_type for conversion-specific costs. Document metric definitions clearly in dashboards. Always specify which cost metric you are using when reporting cross-channel.' }
    ]
  },
